apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: forgejo
  namespace: forgejo
spec:
  parentRefs:
  - name: internet-gateway
    namespace: istio-system
  hostnames:
    - halimede.stenlund.eu
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: forgejo
      port: 3000
      namespace: forgejo
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: forgejo-ssh
  namespace: forgejo
spec:
  parentRefs:
  - name: internet-gateway
    namespace: istio-system
    sectionName: forgejo-ssh
  rules:
  - backendRefs:
    - name: forgejo-ssh
      port: 2222
      namespace: forgejo